left_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
  constraints:
    goal_time: &goal_time_constraint 0.6
    leg_left_1_joint:
      goal: &goal_pos_constraint 0.02
    leg_left_2_joint:
      goal: *goal_pos_constraint
    leg_left_3_joint:
      goal: *goal_pos_constraint
    leg_left_4_joint:
      goal: *goal_pos_constraint
    leg_left_5_joint:
      goal: *goal_pos_constraint
    leg_left_6_joint:
      goal: *goal_pos_constraint

right_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
  constraints:
    goal_time: *goal_time_constraint
    leg_right_1_joint:
      goal: *goal_pos_constraint
    leg_right_2_joint:
      goal: *goal_pos_constraint
    leg_right_3_joint:
      goal: *goal_pos_constraint
    leg_right_4_joint:
      goal: *goal_pos_constraint
    leg_right_5_joint:
      goal: *goal_pos_constraint
    leg_right_6_joint:
      goal: *goal_pos_constraint

torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - torso_1_joint
    - torso_2_joint

  constraints:
    goal_time: *goal_time_constraint
    torso_1_joint:
      goal: *goal_pos_constraint
    torso_2_joint:
      goal: *goal_pos_constraint

head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint

  constraints:
    goal_time: *goal_time_constraint
    head_1_joint:
      goal: *goal_pos_constraint
    head_2_joint:
      goal: *goal_pos_constraint

left_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  constraints:
    goal_time: *goal_time_constraint
    arm_left_1_joint:
      goal: *goal_pos_constraint
    arm_left_2_joint:
      goal: *goal_pos_constraint
    arm_left_3_joint:
      goal: *goal_pos_constraint
    arm_left_4_joint:
      goal: *goal_pos_constraint
    arm_left_5_joint:
      goal: *goal_pos_constraint
    arm_left_6_joint:
      goal: *goal_pos_constraint
    arm_left_7_joint:
      goal: *goal_pos_constraint

right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  constraints:
    goal_time: *goal_time_constraint
    arm_right_1_joint:
      goal: *goal_pos_constraint
    arm_right_2_joint:
      goal: *goal_pos_constraint
    arm_right_3_joint:
      goal: *goal_pos_constraint
    arm_right_4_joint:
      goal: *goal_pos_constraint
    arm_right_5_joint:
      goal: *goal_pos_constraint
    arm_right_6_joint:
      goal: *goal_pos_constraint
    arm_right_7_joint:
      goal: *goal_pos_constraint

right_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: &hand_right_joints
    - hand_right_thumb_joint
    - hand_right_index_1_joint
    - hand_right_index_2_joint
    - hand_right_index_3_joint
    - hand_right_middle_1_joint
    - hand_right_middle_2_joint
    - hand_right_middle_3_joint

  gains:
    hand_right_thumb_joint:    &thumb_gains    {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_index_1_joint:  &finger_1_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_index_2_joint:  &finger_2_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_index_3_joint:  &finger_3_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    hand_right_middle_1_joint: *finger_1_gains
    hand_right_middle_2_joint: *finger_2_gains
    hand_right_middle_3_joint: *finger_3_gains
  joint_trajectory_action_node:
    joints: *hand_right_joints
    constraints:
      goal_time: *goal_time_constraint
      hand_right_thumb_joint:
        goal: *goal_pos_constraint
      hand_right_index_1_joint:
        goal: *goal_pos_constraint
      hand_right_middle_1_joint:
        goal: *goal_pos_constraint
      hand_right_middle_1_joint:
        goal: *goal_pos_constraint

left_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: &hand_left_joints
    - hand_left_thumb_joint
    - hand_left_index_1_joint
    - hand_left_index_2_joint
    - hand_left_index_3_joint
    - hand_left_middle_1_joint
    - hand_left_middle_2_joint
    - hand_left_middle_3_joint

  gains:
    hand_left_thumb_joint:    *thumb_gains
    hand_left_index_1_joint:  *finger_1_gains
    hand_left_index_2_joint:  *finger_2_gains
    hand_left_index_3_joint:  *finger_3_gains
    hand_left_middle_1_joint: *finger_1_gains
    hand_left_middle_2_joint: *finger_2_gains
    hand_left_middle_3_joint: *finger_3_gains
  joint_trajectory_action_node:
    joints: *hand_left_joints
    constraints:
      goal_time: *goal_time_constraint
      hand_left_thumb_joint:
        goal: *goal_pos_constraint
      hand_left_index_1_joint:
        goal: *goal_pos_constraint
      hand_left_middle_1_joint:
        goal: *goal_pos_constraint
