actuators:
  raw_data:
    position_port: act_position
    effort_port: act_current
    position_cmd_port: ref_position
    current_limit_cmd_port: ref_limit_current

e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

force_torque:
  left_ankle_ft:
    frame: leg_left_6_link
    raw_data:
      force_port: force_ankle_left
      torque_port: torque_ankle_left
  right_ankle_ft:
    frame: leg_right_6_link
    raw_data:
      force_port: force_ankle_right
      torque_port: torque_ankle_right
  left_wrist_ft:
    frame: arm_left_7_link
    raw_data:
      force_port: force_wrist_left
      torque_port: torque_wrist_left
  right_wrist_ft:
    frame: arm_right_7_link
    raw_data:
      force_port: force_wrist_right
      torque_port: torque_wrist_right

imu:
  base_imu:
    frame: base_link
    raw_data:
      orientation_port: orientation_base
